applications/events/urls.py
from django.urls import path, include
from applications.events import views

app_name = "events"

urlpatterns = [
    path("eventboard/", views.retrieve_eventboard, name="retrieve_eventboard"),
    path("eventboard/page=<int:page>", views.retrieve_eventboard, name="retrieve_eventboard",),
    path("events/", views.retrieve_event_info, name="retrieve_event_info"),
    path("events/<str:event_id>/", views.retrieve_event_info, name="retrieve_event_info"),
    path("events/<str:event_id>/edit_event/", views.edit_event_info, name="edit_event_info"),
    path("create_event/", views.create_event, name="create_event"),
    path("create_new/confirm/<str:event_id>/", views.confirm_new_event, name="confirm_new_event"),
]

applications/users/urls.py
from django.urls import path
from applications.users import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    #path("login/?next=/<str:next_path>/", views.login, name="login"),
    path("login/", views.login, name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
    #path("mypage/", views.get_mypage, name="mypage"),
    path("mypage/joinlist/", views.retrieve_my_joinlist, name="retrieve_my_joinlist"),
    path("mypage/myhostinglist/", views.retrieve_my_hostinglist, name="retrieve_my_hostinglist"),
    path("mypage/mywatchlist/", views.retrieve_my_watchlist, name="retrieve_my_watchlist"),
    path("mypage/editprofile/", views.edit_profile, name="edit_profile"),
    path("mypage/profile/", views.retrieve_profile, name="retrieve_profile"),
    path("mypage/photos/", views.edit_my_images, name="edit_my_images")
]

project_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("applications.events.urls"), name="events"),
    path("accounts/", include("applications.users.urls"), name="users"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Meetlocals</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    {% block additional_head %}{% endblock %}
    {% block additional_head_2 %}{% endblock %}
    <script>
        var jumpToEventboard = function(){
          console.log("Hi");
          window.alert("hi");
          window.location.href = "http://stackoverflow.com";
        }
    </script>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-light fixed-top">
      <div class="nav-container">
        <div class="row">
          <div class="col-4 col-sm-3 col-md-2 col-lg-2">
            <a class="navbar-brand" href="{% url 'events:retrieve_eventboard'%}">MeetLocals DEMO</a>
          </div>
          <div class="col-8 col-sm-9 col-md-10 col-lg-3">
              <form type="GET" autocomplete="off" action="{{domain_name}}{% url 'events:retrieve_eventboard'%}" id="search_form">
                {% csrf_token %}
                {% render_field search_form.search_string class+="form-control" placeholder="Search hangouts" %}
              </form>
              <button class="navbar-toggler" id="responsive-menu-button" type="button" data-toggle="collapse" data-target="#resposiveNav" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
              </button>
          </div>
          <div class="col-12 col-sm-12 col-md-12 col-lg-7">
            <div class="collapse navbar-collapse" id="resposiveNav">
              <ul class="navbar-nav ml-auto">
                <li>
                {% if DEBUG_MODE %}
                  <span class="nav-link" href="#"><font size="3" color="red">MAINTAINANCE</font></span>
                </li>
                {% endif %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'users:retrieve_my_joinlist'%}">My Page</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'events:create_event'%}">Create Hangout</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Contact</a>
                </li>
                <li class="nav-item">
                  {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                  {% else %}
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                  {% endif %}
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="content-section">
      {% block content %}
      {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 footer">
      <div class="container">
        <p class="m-0 text-center text-white">Amon Otsuki &copy; MeetLocals 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    {% block script_source %}
    {% endblock %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>

</html>