applications/events/urls.py
from django.urls import path, include
from applications.events import views

app_name = "events"

urlpatterns = [
    path("eventboard/", views.retrieve_eventboard, name="retrieve_eventboard"),
    path("eventboard/page=<int:page>", views.retrieve_eventboard, name="retrieve_eventboard",),
    path("events/", views.retrieve_event_info, name="retrieve_event_info"),
    path("events/<str:event_id>/", views.retrieve_event_info, name="retrieve_event_info"),
    path("events/<str:event_id>/edit_event/", views.edit_event_info, name="edit_event_info"),
    path("create_event/", views.create_event, name="create_event"),
    path("create_new/confirm/<str:event_id>/", views.confirm_new_event, name="confirm_new_event"),
]

applications/users/urls.py
from django.urls import path
from applications.users import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    #path("login/?next=/<str:next_path>/", views.login, name="login"),
    path("login/", views.login, name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
    #path("mypage/", views.get_mypage, name="mypage"),
    path("mypage/joinlist/", views.retrieve_my_joinlist, name="retrieve_my_joinlist"),
    path("mypage/myhostinglist/", views.retrieve_my_hostinglist, name="retrieve_my_hostinglist"),
    path("mypage/mywatchlist/", views.retrieve_my_watchlist, name="retrieve_my_watchlist"),
    path("mypage/editprofile/", views.edit_profile, name="edit_profile"),
    path("mypage/profile/", views.retrieve_profile, name="retrieve_profile"),
    path("mypage/photos/", views.edit_my_images, name="edit_my_images")
]

project_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("applications.events.urls"), name="events"),
    path("accounts/", include("applications.users.urls"), name="users"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import JSONField
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

from datetime import datetime
import json


class UserAccountManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, first_name, last_name, password, is_staff, is_superuser):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The email address must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, is_staff=is_staff,
                          is_superuser=is_superuser, date_joined=datetime.now())
        user.set_password(password)
        user.save(using=self._db)
        profile = UserProfile(user=user, first_name=first_name, last_name=last_name, birthday=timezone.now(),
                              where_you_live="", introduction="", profile_image_storage_url="")
        profile.save()
        #request.session.modified = True
        return user

    def create_user(self, email=None, first_name=None, last_name=None, password=None):
        print("create_user()")
        return self._create_user(email=email, first_name=first_name, last_name=last_name, password=password, is_staff=False,
                                 is_superuser=False)

    def create_superuser(self, email, password):
        print("create_superuser()")
        first_name = input("Enter last name: ")
        last_name = input("Enter first name: ")
        return self._create_user(email=email, first_name=first_name, last_name=last_name,
                                 password=password, is_staff=True,
                                 is_superuser=True)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    #profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE, default=None)
    watch_list = JSONField(default=list, blank=True)
    join_list = JSONField(default=list, blank=True)
    hosting_list = JSONField(default=list, blank=True)
    is_staff = models.BooleanField(default=False,
                                   help_text='Designates whether the user is a team staff.')

    is_superuser = models.BooleanField(default=False,
                                        help_text='Designates whether the user can log into this admin site.')

    date_joined = models.DateTimeField(default=None, help_text="Time when the user account is created.")

    #Tell Django that this User uses UserManager instead of the default BaseUserManager
    objects = UserAccountManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    class Meta:
        ordering = ('email',)

    def has_it_in_join_list(self, event_id):
        """
        :param User_obj:
        :param event_id:
        :return: Checks if the user object has event_id in its join_list list.
        """
        user_hangouts = self.join_list
        if event_id in user_hangouts:
            #print(self, event_id, "in watch_list:", watch_list)
            return True
        else:
            #print(self, event_id, "NOT in watch_list:", watch_list)
            return False


    def has_it_in_watch_list(self, event_id):
        """
        :param User_obj:
        :param event_id:
        :return: Checks if the user object has event_id in its join_list list.
        """
        watch_list = self.watch_list
        if event_id in watch_list:
            #print(self, event_id, "in watch_list:", watch_list)
            return True
        else:
            #print(self, event_id, "NOT in watch_list:", watch_list)
            return False


    def add_to_join_list(self, event_id):
        user_hangouts = self.join_list
        user_hangouts.append(event_id)
        self.join_list = user_hangouts
        #print(self, "added", event_id, "to its join list.")
        self.save()

    def remove_from_join_list(self, event_id):
        user_hangouts = self.join_list
        user_hangouts.remove(event_id)
        self.join_list = user_hangouts
        #print(self, "removed", event_id, "from its join list.")
        self.save()

    def add_to_watch_list(self, event_id):
        watch_list = self.watch_list
        watch_list.append(event_id)
        self.watch_list = watch_list
        #print(self, "added", event_id, "to its watch list.")
        self.save()

    def remove_from_watch_list(self, event_id):
        watch_list = self.watch_list
        watch_list.remove(event_id)
        self.watch_list = watch_list
        #print(self, "removed", event_id, "from its watch list.")
        self.save()

    def add_to_hosting_list(self, event_id):
        hosting_list = self.hosting_list
        hosting_list.append(event_id)
        self.hosting_list = hosting_list
        #print(self, "added", event_id, "to hosting_list")
        self.save()


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=False, related_name="profile")
    first_name = models.CharField(blank=False, default="", max_length=30)
    last_name = models.CharField(blank=False, default="", max_length=30)
    middle_name = models.CharField(blank=True, default="", max_length=30)
    birthday = models.DateField(blank=True, default=None)
    where_you_live = models.CharField(default="", max_length=160, blank=True)
    introduction = models.CharField(default="", max_length=300, blank=True)
    profile_image_storage_url = models.CharField(default="", max_length=160)

    #Once the sender(user)'s save() is executed, this method is going to run.
    # @receiver(post_save, sender=User)
    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         Profile.objects.create(user=instance)
    #
    # @receiver(post_save, sender=User)
    # def save_user_profile(sender, instance, **kwargs):
    #     instance.profile.save()

applications/users/forms.py
import os
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from applications.users.models import User, UserProfile
import datetime
from PIL import Image
from applications.users import views_support_scripts
from django.conf import settings

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email',)


    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("The email has already been taken.")
        else:
            return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if not password2:
            raise forms.ValidationError("Please confirm your password.")
        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match.")
        return password2

    # def save(self, commit=True):
    #     self.cleaned_data["date_joined"] = datetime.datetime.now()
    #     self.cleaned_data["is_active"] = True
    #     self.cleaned_data["is_staff"] = False
    #     self.cleaned_data["is_superuser"] = False
    #     return super(CustomUserCreationForm, self).save(commit)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email',)

class ProfileForm(forms.ModelForm):
    birthday = forms.DateField(widget=forms.HiddenInput())
    class Meta():
        model = UserProfile
        fields = ("first_name", "last_name", "middle_name", 'birthday', 'where_you_live', 'introduction',)
        widgets = {
            "introduction": forms.Textarea(),
        }

    # def save(self, commit=True):
    #     new_profile = super(ProfileForm, self).save(commit=False)
    #     old_profile = UserProfile.objects.filter(id=new_profile.id)
    #     # print("Saving profile of", user)
    #     # print("The user's profile =", user.profile)
    #     # print([f.name for f in user._meta.get_fields()])
    #     new_profile_fields = [f for f in new_profile._meta.get_fields()]
    #     print("FIELDS of user profile")
    #     for new_profile_field in new_profile_fields:
    #          = profile._meta.get_field(field_name)
    #         print(field_name + ": " + str(field_object.value_from_object(profile)))
    #     if commit == True:
    #         UserProfile.objects.filter(id=profile.id)
    #         print("Profile saved")
    #     return profile

class ProfileImageForm(forms.Form):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    image = forms.ImageField()
    def save_image_of(self, user):
        img_format = ".jpg"
        stored_time = datetime.datetime.now().strftime("%m%d%Y%H%M%S")
        print("time format:", stored_time)

        image_x = self.cleaned_data.get('x')
        image_y = self.cleaned_data.get('y')
        image_width = self.cleaned_data.get('width')
        image_height = self.cleaned_data.get('height')
        #print("Coordinates:", image_x, image_y, image_width, image_height)
        # Resize the image and store it in media dir.
        image = Image.open(self.cleaned_data.get('image')).convert('RGB')
        cropped_image = image.crop((image_x, image_y, image_width + image_x, image_height + image_y))
        resized_image = cropped_image.resize((500, 500), Image.ANTIALIAS)
        file_name = "profileImg_" + str(user.id) + "_" + stored_time + img_format
        image_storage_path = os.path.join(settings.MEDIA_ROOT, settings.PROFILE_IMAGE_DIR, file_name)
        print("image_storage_path", image_storage_path)
        image_storage_url = settings.MEDIA_URL + settings.PROFILE_IMAGE_URL.lstrip("/") + file_name + "/"
        print("Profile storage", settings.PROFILE_IMAGE_URL, "|", image_storage_url)
        try:
            resized_image.save(image_storage_path, format="JPEG")  # Image.save() saves the image in a file at the given path(event.image.path)
        except Exception as e:
            #print("Image failed to be saved:", e)
            raise forms.ValidationError("Error occured when saving the image")
        return str(image_storage_url)

templates/users/edit_images.html
{% extends "users/mypage.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block additional_head_2 %}
    <script src="{% static 'js/jquery.ymdpulldown.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/1.0.0/cropper.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/1.0.0/cropper.min.css" rel="stylesheet" type="text/css" media="all"/>
{% endblock %}

{% block dashboard %}
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Profile picture</h3>
<form method="POST" id="user-profile-form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row image-section">
      <div class="col-xs-12 col-md-4">
        <img class="profile-img" src="{{profile_image_storage_url}}"/>
      </div>
      <div class="col-xs-12 col-md-7">
        <p>Your picture is an important part of your profile because it gives other people a sense of who you are like. Please pick a photo that shows your face clearly and make sure that it does not show any personal information that you would not like to be disclosed.</p>
      </div>
    </div>
    <div class="form-group">
      {% render_field profile_image_form.image class+="form-control"%}
      {% render_field profile_image_form.x class+="form-control"%}
      {% render_field profile_image_form.y class+="form-control"%}
      {% render_field profile_image_form.width class+="form-control"%}
      {% render_field profile_image_form.height class+="form-control"%}
    </div>
    <br>
    <button type="submit" class="btn btn-warning">Save</button>

    <div class="modal fade" id="modalCrop">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Crop the image for your profile</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <i class="far fa-window-close"></i>
            </button>
          </div>
          <div class="modal-body">
            <img src="" id="image" style="max-width: 100%;">
          </div>
          <div class="modal-footer">
            <div class="btn-group pull-left" role="group">
              <button type="button" class="btn btn-default js-zoom-in">
                <i class="fas fa-search-plus"></i>
              </button>
              <button type="button" class="btn btn-default js-zoom-out">
                <i class="fas fa-search-minus"></i>
              </button>
            </div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
            <button type="button" class="btn btn-primary js-crop-and-upload" id="crop_button">Crop image</button>
          </div>
        </div>
      </div>
    </div>
</form>

<script>
$(function() {
  $("#birthday-year").ymdpulldown({
                startyear:1920,
              });
  $("#birthday-month").ymdpulldown();
  $("#birthday-day").ymdpulldown();
});

$('#user-profile-form').submit(function() {
    var year = document.getElementById('birthday-year').value;
    var month = document.getElementById('birthday-month').value;
    var day = document.getElementById('birthday-day').value;
    var $birthdayForm = document.getElementById('id_birthday');
    $birthdayForm.value = year + "-" + month + "-" + day;
    return true;
});

/* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
$("#id_image").change(function () {
  if (this.files && this.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $("#image").attr("src", e.target.result);
      $("#modalCrop").modal("show");

    }
    reader.readAsDataURL(this.files[0]);
  }
});

/* SCRIPTS TO HANDLE THE CROPPER BOX */
var $image = $("#image");
var cropBoxData;
var canvasData;
$("#modalCrop").on("shown.bs.modal", function () {
  $image.cropper({
    viewMode: 1,
    aspectRatio: 1/1,
    minCropBoxWidth: 70,
    minCropBoxHeight: 43,
    ready: function () {
      $image.cropper("setCanvasData", canvasData);
      $image.cropper("setCropBoxData", cropBoxData);
    }
  });
}).on("hidden.bs.modal", function () {
  cropBoxData = $image.cropper("getCropBoxData");
  canvasData = $image.cropper("getCanvasData");
  $image.cropper("destroy");
});

$(".js-zoom-in").click(function () {
  $image.cropper("zoom", 0.1);
});

$(".js-zoom-out").click(function () {
  $image.cropper("zoom", -0.1);
});

/* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
$("#crop_button").click(function () {
  var cropData = $image.cropper("getData");
  $("#id_x").val(cropData["x"]);
  $("#id_y").val(cropData["y"]);
  $("#id_height").val(cropData["height"]);
  $("#id_width").val(cropData["width"]);
  //console.log($("#id_x").val(), $("#id_y").val(), $("#id_height").val(), $("#id_width").val());
  $("#modalCrop").modal("hide");
  //console.log(cropData["x"], cropData["y"], cropData["height"], cropData["width"])
});
</script>
{% endblock %}

templates/users/edit_profile.html
{% extends "users/mypage.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block additional_head_2 %}
    <script src="{% static 'js/jquery.ymdpulldown.js' %}"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/1.0.0/cropper.min.css" rel="stylesheet" type="text/css" media="all"/>
{% endblock %}

{% block dashboard %}
<p>Edit your profile</p>
<form method="POST" id="user-profile-form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {{profile_form.first_name.label}}:
        {% render_field profile_form.first_name class+="form-control"%}
    </div>
    <div class="form-group">
        {{profile_form.last_name.label}}:
        {% render_field profile_form.last_name class+="form-control" %}
    </div>
    <div class="form-group">
        {{profile_form.middle_name.label}}:
        {% render_field profile_form.middle_name class+="form-control"%}
    </div>

    <div class="form-group">
        <label for="birthday-year birthday-month birthday-day">Birthday:</label>
        <div class="input-group">
            <select id="birthday-year" class="form-control" data-choice="year" data-select="{{birthday_year}}"></select>
            <select id="birthday-month" class="form-control" data-choice="month" data-select="{{birthday_month}}"></select>
            <select id="birthday-day" class="form-control" data-choice="day" data-select="{{birthday_day}}"></select>
            {% render_field profile_form.birthday class+="form-control"%}
        </div>
    </div>

    <div class="form-group">
        <label for="id_where_you_live">Area you live in:</label>
        {% render_field profile_form.where_you_live class+="form-control" %}
        *This information will be public.
    </div>
    <label for="id_introduction">Introduce yourself:</label>
    <div class="form-group">
        {% render_field profile_form.introduction class+="form-control" %}
    </div>
    <div class="form-group">
      {% render_field profile_image_form.image class+="form-control"%}
      {% render_field profile_image_form.x class+="form-control"%}
      {% render_field profile_image_form.y class+="form-control"%}
      {% render_field profile_image_form.width class+="form-control"%}
      {% render_field profile_image_form.height class+="form-control"%}
    </div>
    <br>
    <button type="submit" class="btn btn-warning custom-long-button">Save</button>

    <div class="modal fade" id="modalCrop">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Crop the image for your profile</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <i class="far fa-window-close"></i>
            </button>
          </div>
          <div class="modal-body">
            <img src="" id="image" style="max-width: 100%;">
          </div>
          <div class="modal-footer">
            <div class="btn-group pull-left" role="group">
              <button type="button" class="btn btn-default js-zoom-in">
                <i class="fas fa-search-plus"></i>
              </button>
              <button type="button" class="btn btn-default js-zoom-out">
                <i class="fas fa-search-minus"></i>
              </button>
            </div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
            <button type="button" class="btn btn-primary js-crop-and-upload" id="crop_button">Crop image</button>
          </div>
        </div>
      </div>
    </div>
</form>

<script>
$(function() {
  $("#birthday-year").ymdpulldown({
                startyear:1920,
              });
  $("#birthday-month").ymdpulldown();
  $("#birthday-day").ymdpulldown();
});

$('#user-profile-form').submit(function() {
    var year = document.getElementById('birthday-year').value;
    var month = document.getElementById('birthday-month').value;
    var day = document.getElementById('birthday-day').value;
    var $birthdayForm = document.getElementById('id_birthday');
    $birthdayForm.value = year + "-" + month + "-" + day;
    return true;
});

/* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
$("#id_image").change(function () {
  if (this.files && this.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $("#image").attr("src", e.target.result);
      $("#modalCrop").modal("show");

    }
    reader.readAsDataURL(this.files[0]);
  }
});

/* SCRIPTS TO HANDLE THE CROPPER BOX */
var $image = $("#image");
var cropBoxData;
var canvasData;
$("#modalCrop").on("shown.bs.modal", function () {
  $image.cropper({
    viewMode: 1,
    aspectRatio: 1/1,
    minCropBoxWidth: 70,
    minCropBoxHeight: 43,
    ready: function () {
      $image.cropper("setCanvasData", canvasData);
      $image.cropper("setCropBoxData", cropBoxData);
    }
  });
}).on("hidden.bs.modal", function () {
  cropBoxData = $image.cropper("getCropBoxData");
  canvasData = $image.cropper("getCanvasData");
  $image.cropper("destroy");
});

$(".js-zoom-in").click(function () {
  $image.cropper("zoom", 0.1);
});

$(".js-zoom-out").click(function () {
  $image.cropper("zoom", -0.1);
});

/* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
$("#crop_button").click(function () {
  var cropData = $image.cropper("getData");
  $("#id_x").val(cropData["x"]);
  $("#id_y").val(cropData["y"]);
  $("#id_height").val(cropData["height"]);
  $("#id_width").val(cropData["width"]);
  console.log($("#id_x").val(), $("#id_y").val(), $("#id_height").val(), $("#id_width").val());
  $("#modalCrop").modal("hide");
  console.log(cropData["x"], cropData["y"], cropData["height"], cropData["width"])
});
</script>
{% endblock %}

templates/users/my_hangouts.html
{% extends "users/mypage.html" %}
{% load staticfiles %}

{% block dashboard %}
<h2>Hangouts you signed up to join</h2><br>
<div class="row">
 {% for event in events %}
        <div class="col-md-3 col-xs-3 board-item">
          <div class="card h-100">
            <a href="{% url 'events:retrieve_event_info' event_id=event.event_id%}"><img class="card-img-top" src="{{event.image_storage_url}}" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{% url 'events:retrieve_event_info' event_id=event.event_id%}">{{event.name}}</a>
              </h4>
              <p>{{event.date}}<br>{{event.start_time}} - {{event.end_time}}</p>
            </div>
          </div>
        </div>
 {% endfor %}
    </div>

{% endblock %}

templates/users/my_hostinglist.html
{% extends "users/mypage.html" %}
{% load staticfiles %}

{% block dashboard %}
<h2 class="inline-center-align">Hangouts you are hosting</h2><hr>
<div class="row">
 {% for event in events %}
        <div class="col-md-3 col-xs-3 board-item">
          <div class="card h-100">
            <a href="{% url 'events:retrieve_event_info' event_id=event.event_id%}"><img class="card-img-top" src="{{event.image_storage_url}}" alt=""></a>
            <div class="card-body">
              <p class="card-title">
                <a href="{% url 'events:retrieve_event_info' event_id=event.event_id%}">{{event.name}}</a>
              </p><hr>
              <p>{{event.start_date}}</p>
            </div>
          </div>
        </div>
 {% endfor %}
    </div>

{% endblock %}

templates/users/my_profile.html
{% extends "users/mypage.html" %}
{% load staticfiles %}

{% block dashboard %}
<h3 class="inline-center-align">Your profile</h3><hr>
    <div class="form-group">
        <label>First name:&nbsp&nbsp{{profile.first_name}}</label><br>
        <label>*This information will be public.</label>
        <p></p>
        <hr>
    </div>
    <div class="form-group">
        <label>Last name:&nbsp&nbsp{{profile.last_name}}</label><br>
        <label>*This information will be public.</label>
        <hr>
    </div>
    <div class="form-group">
        <label>Middle name:&nbsp&nbsp{{profile.middle_name}}</label><br>
        <label>*This information will be public.</label>
        <hr>
    </div>
    <div class="form-group">
        <label>Birthday:&nbsp&nbsp{{profile.birthday}}</label><br>
        <label>*This information will only be used for our data analysis purpose.</label>
        <hr>
    </div>
    <div class="form-group">
        <label for="id_where_you_live">Where you are from:&nbsp&nbsp{{profile.where_you_live}}</label><br>
        <label>*This information will be public.</label>
        <hr>
    </div>
    <div>
        <label for="id_introduction">Introduce yourself:&nbsp&nbsp{{profile.introduction}}</label><br>
        <label>*This information will be public.</label><br>
    </div><br>
    <form action="{% url 'users:edit_profile'%}">
        <button type="submit" class="btn btn-warning custom-long-button">Edit</button>
    </form>
{% endblock %}

templates/users/mypage.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block additional_head %}
    <link href="{% static 'css/my_page.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row row-option">
    <div class="col-xs-12 col-md-2" >
      <div id="sidebar">
        <p>My page</p><hr>
        <a href="{% url 'users:retrieve_my_hostinglist'%}">Hosted by me</a><hr>
        <a href="{% url 'users:retrieve_my_joinlist'%}">Hangouts</a><hr>
        <a href="{% url 'users:retrieve_my_watchlist'%}">Watch List</a><hr>
        <a href="{% url 'users:retrieve_profile'%}">Profile</a><hr>
        <a href="{% url 'users:edit_my_images'%}">Photos</a><hr>
      </div>
    </div>
    <div class="col-xs-12 col-md-9 dashboard">
          {% block dashboard %}
          {% endblock %}
    </div>
</div>

{% endblock %}

templates/users/user_login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block additional_head %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="container">
    <div class="jumbotron add-margin-top">
      <h1>Login</h1>
        <form method="post" action="{% url 'users:login' %}">
          {% csrf_token %}
          <label for="email">Email:</label>
          <input type="email" name="email" placeholder="Username"><br>
          <label for="password">Password:</label>
          <input type="password" name="password">
          <input type="submit" name="" value="Login">

        </form>
      <a href="{% url 'users:signup'%}"><p>Don't have an account? Sign up here.</p></a>
    </div>
  </div>
{% endblock %}