applications/events/urls.py
from django.urls import path, include
from applications.events import views

app_name = "events"

urlpatterns = [
    path("eventboard/", views.retrieve_eventboard, name="retrieve_eventboard"),
    path("eventboard/page=<int:page>", views.retrieve_eventboard, name="retrieve_eventboard",),
    path("events/", views.retrieve_event_info, name="retrieve_event_info"),
    path("events/<str:event_id>/", views.retrieve_event_info, name="retrieve_event_info"),
    path("events/<str:event_id>/edit_event/", views.edit_event_info, name="edit_event_info"),
    path("create_event/", views.create_event, name="create_event"),
    path("create_new/confirm/<str:event_id>/", views.confirm_new_event, name="confirm_new_event"),
]

project_base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("applications.events.urls"), name="events"),
    path("accounts/", include("applications.users.urls"), name="users"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/events/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
#--------------------------------------------------------------------------------------------------------
import datetime
import os
from random import randint
import string
#--------------------------------------------------------------------------------------------------------
from imagekit_cropper.fields import ImageCropField, InstanceSpecField, InstanceFormatSpecField
from imagekit_cropper.processors import PositionCrop, PositionAndFormatCrop, FormatProcessor
from taggit.managers import TaggableManager
#--------------------------------------------------------------------------------------------------------
#                                   Support functions for models.

#HANGOUT_IMAGE_DIR = 'hangout_image/' - NOW DEFINED IN settings
# def get_image_storage_path(instance, filename):
#     print("get_image_storage_path: instance =", type(instance), instance)
#     print("event_id", instance.event_id)
#     return os.path.join(HANGOUT_IMAGE_DIR, str(instance.event_id),)

#--------------------------------------------------------------------------------------------------------

class Location(models.Model):
    location_name = models.CharField(default="", max_length=30, blank=False,)
    #slug = models.SlugField(max_length=255, null=True)
    address = models.CharField(default="", max_length=120, blank=False,)

    def set_location_name(self, location_name):
        self.location_name = location_name

    def __str__(self):
        return str(self.location_name)

class Event(models.Model):
    event_id = models.CharField(default="XXXXXXXXXX", max_length=10, blank=False, unique=True)
    name = models.CharField(max_length=150, blank=False)
    start_date = models.DateField(default=None, blank=False)
    end_date = models.DateField(default=None, blank=False)
    start_time = models.TimeField(default=None, blank=False)
    end_time = models.TimeField(default=None, blank=False)
    #image = models.ImageField(upload_to=get_image_storage_path, default="place_holders/place_holder_700x400.png")
    image_storage_url = models.CharField(default="", max_length=160, blank=False)
    language = models.CharField(default="", max_length=50, blank=False)
    location = models.OneToOneField(Location, on_delete=models.CASCADE, blank=False, related_name="event")
    description = models.CharField(max_length=1000, blank=False)
    tags = TaggableManager() #String of tags splitted by ","
    host_name = models.CharField(max_length=160, default="", blank=False)
    """↑Update: Delete"""
    host = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    #slug = models.SlugField(max_length=255, null=True)##WHat's this?

    def is_one_day_hangout(self):
        if str(self.start_date) == str(self.end_date):
            return True
        else:
            return False

    def create_event(self, name, start_time, end_time, location, description, host_name, host):
        #self.event_id = #Do not allow duplicates
        self.name = name
        self.start_time = start_time
        self.end_time = end_time
        self.location = location
        self.description = description
        self.host_name = host_name
        """Update"""
        self.host = None

    def __str__(self):
        return str(self.name)

applications/events/forms.py
#Django libs
from django import forms
from applications.events.models import Event, Location
from applications.users.models import User
from django.conf import settings
#Python libs
import random
import string
import datetime
from PIL import Image
import os
#Other additional libs
from bootstrap_datepicker_plus import DateTimePickerInput

timeTuples = ('00:00', '00:30', '01:00', '01:30', '02:00', '02:30', '03:00', '03:30', '04:00', '04:30', '05:00', '05:30', '06:00', '06:30', '07:00', '07:30', '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30')

class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.issued_event_id = "XXXXXXXXXX"
        super(EventForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        """
        :param commit: Wheather or not to commit to the DB
        :return: event obj
                This method is responsible for issuing event_id and cropping the image and saving it in MEDIA DIR.
        """
        #Issue a new event ID. Bind this form to the ID.
        if self.issued_event_id == "XXXXXXXXXX":
            event_id_issued_successfully = False
            while not event_id_issued_successfully:
                event_id = self.generate_event_id()
                if not Event.objects.filter(event_id=event_id).exists(): # Check if this checks for the duplicates
                    self.issued_event_id = event_id
                    event_id_issued_successfully = True
        if commit:
            event = super().save(commit=False)
            event.event_id = self.issued_event_id
            event = super().save(commit=True)
        else:
            event = super().save(commit=False)
        event.event_id = self.issued_event_id
        return event
        # except Exception as e:
        #     print("save() ERROR!!!")
        #     print(str(e))

    def generate_event_id(self):
        event_id = ""
        for i in range(10):
            if random.randint(0, 1) == 0:
                event_id += str(random.randint(0, 9))
            else:
                event_id += random.choice(string.ascii_uppercase)
        return event_id

    class Meta(): #Configures the model to work with
        model = Event
        fields = ("name",  "start_date", "end_date", "start_time", "end_time", "language", "description", "tags",)
        widgets = {
                   "description": forms.Textarea(),
                   "start_time": forms.Select(),
                   "end_time": forms.Select(),
                   }
        # help_text = {
        #     "start_time": "Please clear the end time before you change the start time",
        # }

class EventEditForm(forms.ModelForm):
    class Meta(): #Configures the model to work with
        model = Event
        fields = ("name",  "start_date", "end_date", "start_time", "end_time", "language", "description", "tags",)
        widgets = {
                   "description": forms.Textarea(),
                   "start_time": forms.Select(),
                   "end_time": forms.Select(),
                   }

class LocationForm(forms.ModelForm):
    class Meta(): #Configures the model to work with
        model = Location
        fields = ("location_name", "address")


class EventImageForm(forms.Form):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    image = forms.ImageField()
    def save_image_of(self, event):
        img_format = ".jpg"
        stored_time = datetime.datetime.now().strftime("%m%d%Y%H%M%S")
        #print("time format:", stored_time)
        #print("cleaned_date:", self.cleaned_data)
        image_x = self.cleaned_data.get('x')
        image_y = self.cleaned_data.get('y')
        image_width = self.cleaned_data.get('width')
        image_height = self.cleaned_data.get('height')
        #print("Coordinates:", image_x, image_y, image_width, image_height)
        # Resize the image and store it in media dir.
        image = Image.open(self.cleaned_data.get('image')).convert('RGB')  # event.image
        cropped_image = image.crop((image_x, image_y, image_width + image_x, image_height + image_y))
        resized_image = cropped_image.resize((700, 400), Image.ANTIALIAS)

        file_name = event.event_id + "_" + stored_time + img_format
        image_storage_path = os.path.join(settings.MEDIA_ROOT, settings.HANGOUT_IMAGE_DIR, file_name)
        image_storage_url = settings.MEDIA_URL + settings.HANGOUT_IMAGE_URL + file_name + "/"
        try:
            print("Saving img at PATH:", image_storage_path)
            print("Saving img at URL:", image_storage_url)
            resized_image.save(image_storage_path, format="JPEG")  # Image.save() saves the image in a file at the given path(event.image.path)
        except Exception:
            raise forms.ValidationError("This type of image file cannot be used.")
        return str(image_storage_url)


class BookmarkRequestForm(forms.Form):
    bookmark_request = forms.CharField(widget=forms.HiddenInput)
    def request_type(self):
        return self.cleaned_data.get('bookmark_request')

class SearchForm(forms.Form):
    search_string = forms.CharField()

templates/events/edit_event_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additional_head %}
    <link href="{% static 'css/event_info.css' %}" rel="stylesheet">
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
{% endblock %}
{% block content %}
  <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-9" >
          <div class="box" >
            <center><h1>{{event.name}}</h1></center>
            <center><img alt="Hangout Image" src={{event.image_storage_url}}/></center>
            <div class="event_info"><br>
              <span>Date & Time:&nbsp;&nbsp;&nbsp;{{event.start_date}}/{{event.start_time}}&nbsp;-&nbsp;{{event.end_date}}/{{event.end_time}}</span><br>
              <span>Language:&nbsp;{{event.language}}</span><br>
              <span>Tags: {{event.tags.all|join:", "}}</span><br>
              <hr>
              <br>
            </div>
            <center><font size="5">About this hangout</font></center>
            <br>
            <p>{{event.description}}</p>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

templates/events/event_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additional_head %}
    <link href="{% static 'css/event_info.css' %}" rel="stylesheet">
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
{% endblock %}
{% block content %}
  <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-9" >
          <div class="box" >
            <center><h1>{{event.name}}</h1></center>
            <center><img alt="Hangout Image" src={{event.image_storage_url}}/></center>
            <div class="event_info"><br>
              <span>Date & Time:&nbsp;&nbsp;&nbsp;{{event.start_date}}/{{event.start_time}}&nbsp;-&nbsp;{{event.end_date}}/{{event.end_time}}</span><br>
              <span>Language:&nbsp;{{event.language}}</span><br>
              <span>Tags: {{event.tags.all|join:", "}}</span><br>
              <hr>
              <br>
            </div>
            <center><font size="5">About this hangout</font></center>
            <br>
            <p>{{event.description}}</p>
            <br>
            {% if is_host %}
            <a style="text-decoration: none;" href="{% url 'events:edit_event_info' event_id=event.event_id%}"><button type="button" class="btn btn-warning btn-lg" id="watch-button">Edit this hangout</button></a>
            {% else %}
              <div class="row">
                  <div class="col-xs-12 col-md-12 col-lg-6">
                    {% if added_to_watch_list %}
                      <button type="button" class="btn btn-warning btn-lg event-page-button" id="watch-button">Remove from watch list</button>
                    {% else %}
                      <button type="button" class="btn btn-warning btn-lg event-page-button" id="watch-button">Add to watch list</button>
                    {% endif %}
                  </div>
                  <div class="col-xs-12 col-md-12 col-lg-6">
                    {% if added_to_join_list %}
                      <button type="button" class="btn btn-warning btn-lg event-page-button" id="join-button">&nbsp;Cancel this event&nbsp;</button>
                    {% else %}
                       <button type="button" class="btn btn-warning btn-lg event-page-button" id="join-button">&nbsp;Join this event!&nbsp;</button>
                    {% endif %}
                  </div>
                </div>
                <form id="bookmark-request-form" method="POST">
                  {% csrf_token %}
                  {{bookmark_request_form}}
                </form>
            {% endif %}
          </div>
        </div>
        <div class="col-xs-12 col-md-3">
          <div class="box">
            <center><p>Host<br>{{host_name}}</p></center>
            <img src="{{host_img_url}}" alt="{{no_photo_icon_url}}" class="host_img"/>
          </div>
        </div>
      </div>
    </div>
<script>
$(document).ready
(function($)
  {
      var $watchButton = $('#watch-button');
      var $joinButton = $('#join-button');
      var $bookmarkForm = $('#bookmark-request-form');
      var $bookmarkRequest = $("#id_bookmark_request")
      $watchButton.click
      (function()
          {
            $bookmarkRequest.val("add-to-watch");
            console.log("WatchButton");
            $bookmarkForm.submit();
          }
      );

      $joinButton.click
      (function()
          {
            $bookmarkRequest.val("join-event");
            $bookmarkForm.submit();
            console.log("JoinButton");
          }
      );
  }
);
</script>
{% endblock %}

templates/events/eventboard.html
{% extends 'base.html' %}
{% load staticfiles %}

 {% block additional_head %}
    <link href="{% static 'css/eventboard.css' %}" rel="stylesheet">
  {% endblock %}

  {% block content%}
    <!-- Page Content -->
    <div class="container">
      <!-- Page Heading -->
      <center>
      </center>
      <center>

        <h1 class="my-4">
          {% if is_searching %}
            {% if has_no_result %}
              <span>Sorry, "{{search_string}}" did not match any results.</span>
            {% else %}
              <span>Search result of "{{search_string}}"</span>
            {% endif %}
          {% else %}
            <span>Upcoming Hangouts</span>
          {% endif %}
          </h1></center>
      <!-- event info -->
      <div class="row">
        {% for event in events %}
        <div class="col-lg-3 col-md-4 col-sm-6 board-item">
          <div class="card h-100">
            <a href="{% url 'events:retrieve_event_info' event_id=event.event_id%}"><img class="card-img-top" src="{{event.image_storage_url}}" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <p class="card-title"><a href="{% url 'events:retrieve_event_info' event_id=event.event_id%}">{{event.name}}</a></p>
              </h4>
              <p>{{event.start_date}}<br>{{event.start_time}} - {{event.end_time}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

      <!-- Pagination -->
        <div class="text-xs-center" id="pagination">
          <ul class="pagination justify-content-center">
            {% if page_has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ current_page_num|add:-1 }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            {% endif %}
            {% for page_num in page_range %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_num }}">{{page_num}}</a>
              </li>
            {% endfor %}
            {% if page_has_next %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ current_page_num|add:1 }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
            {% endif %}
          </ul>
         </div>
    </div>
  {% endblock %}

templates/events/new_event_confirmation.html
{% extends 'base.html' %}
{% load staticfiles  %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/new_event_confirmation.css' %}">
{% endblock %}

{% block content %}
    <img class="card-img-top" src="{{event.image_storage_url}}" alt="">
{% endblock %}

templates/events/new_event_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/new_event_form.css' %}">
    <link href="{% static 'vendor/bootstrap/css/bootstrap-datepicker.min.css' %}" rel="stylesheet">
    <script src="{% static 'vendor/bootstrap/js/bootstrap-datepicker.min.js' %}"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/1.0.0/cropper.min.css" rel="stylesheet" type="text/css" media="all"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/1.0.0/cropper.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
{% endblock %}

{% block content %}
<div class="col-md-6 offset-md-3">
    {% if event_form.errors %}
        {% for field in event_form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in event_form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    {% if event_form.errors %}
    {% for field in event_form %}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
    <p><b>Please enter the information to host a hangout.</b></p>
    <form method="POST" enctype="multipart/form-data" id="formUpload" autocomplete="off">
        {% csrf_token %}



        <label for="id_name">Hangout name</label>
        <div class="form-group">
            {% render_field event_form.name class+="form-control" placeholder="Name of the event"%}
        </div>
        {{location_form.location_name.label}}
        <div class="form-group">
            {% render_field location_form.location_name class+="form-control" placeholder="Area or name of a place" %}
        </div>
        {{location_form.address.label}}
        <div class="form-group">
            {% render_field location_form.address class+="form-control" placeholder="Exact address of the location"%}
        </div>
        <label for="id_start_date id_start_time">Start at</label>
        <div class="form-group">
            <div class="input-group-mb3 input-group-append" id="start-datetimepicker" data-target-input="nearest">
            {% render_field event_form.start_date class+="form-control datetimepicker-input" id="start-date" placeholder="Click the calendar"%}
                <div class="input-group-append" id="start-datepicker" data-target="#start-date" data-toggle="datetimepicker">
                    <span class="input-group-text">
                    <i class="fas fa-calendar-alt"></i>
                    </span>
                </div>
            {% render_field event_form.start_time class+="form-control" id="start-time" placeholder="Click the clock"%}
                <div class="input-group-append" id="start-timepicker" data-target="#start-time" data-toggle="datetimepicker">
                    <span class="input-group-text">
                        <i class="fas fa-clock"></i>
                    </span>
                </div>
            </div>
        </div>
        <label for="id_end_date id_end_time">End at</label>
        <div class="form-group">
            <div class="input-group-mb3 input-group-append" id="end-datetimepicker">
            {% render_field event_form.end_date class+="form-control" id="end-date" placeholder="Click the calendar" %}
                <div class="input-group-append" id="end-datepicker" data-target="#end-date" data-toggle="datetimepicker">
                    <span class="input-group-text">
                    <i class="fas fa-calendar-alt"></i>
                    </span>
                </div>
            {% render_field event_form.end_time class+="form-control" id="end-time" placeholder="Click the clock"%}
                <div class="input-group-append" id="end-timepicker" data-target="#end-time" data-toggle="datetimepicker">
                    <span class="input-group-text">
                        <i class="fas fa-clock"></i>
                    </span>
                </div>
            </div>

        </div>
            {{event_form.language.label}}
        <div class="form-group">
            {% render_field event_form.language class+="form-control" placeholder="Languages used for the hangout."%}
        </div>
        {{event_form.description.label}}
        <div class="form-group">
            {% render_field event_form.description class+="form-control" placeholder="What is this hangout about?"%}
        </div>

        {{event_form.tags.label}}
        <div class="form-group">
            {% render_field event_form.tags class+="form-control" placeholder="Separate with commas. e.g) BBQ, outdoor"%}
        </div>
        <div class="form-group">
            <div class="custom-file">
            {% render_field event_image_form.image class="custom-file-input"%}
            {% render_field event_image_form.x %}
            {% render_field event_image_form.y %}
            {% render_field event_image_form.width %}
            {% render_field event_image_form.height %}
            <label for="id_image" class="custom-file-label">Image</label>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-warning btn-lg btn-block">Create a hangout!</button>
        </div>

<script>
/* SCRIPT FOR DATEPICKER */

/*Initialize timepickers*/
var timeChoices = ['12:00 AM', '12:30 AM', '01:00 AM', '01:30 AM', '02:00 AM', '02:30 AM', '03:00 AM', '03:30 AM',
                  '04:00 AM', '04:30 AM', '05:00 AM', '05:30 AM', '06:00 AM', '06:30 AM', '07:00 AM', '07:30 AM',
                  '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
                  '12:00 PM', '12:30 PM', '01:00 PM', '01:30 PM', '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
                 '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM', '06:00 PM', '06:30 PM', '07:00 PM', '07:30 PM',
                 '08:00 PM', '08:30 PM', '09:00 PM', '09:30 PM', '10:00 PM', '10:30 PM', '11:00 PM', '11:30 PM']

var startTimePicker = $('#start-time');
var endTimePicker = $('#end-time');

var initStartTimePicker = function(){
  startTimePicker.empty();
  timeChoices.forEach(function(d){
    choiceNode = document.createElement("option");
    textNode = document.createTextNode(d);
    choiceNode.appendChild(textNode);
    startTimePicker.append(choiceNode);
  });
};

var initEndTimePicker = function(){
  endTimePicker.empty();
  timeChoices.forEach(function(d){
    choiceNode = document.createElement("option");
    textNode = document.createTextNode(d);
    choiceNode.appendChild(textNode);
    endTimePicker.append(choiceNode);
  });
};

//Adjust endTimePicker so its value does not go before the starting time.
var adjustEndTimerPicker = function(){
  endTimePicker.empty();
  startTimeIndex = timeChoices.indexOf(startTimePicker.val());
  timeChoices.slice(startTimeIndex + 1, timeChoices.length).forEach(function(d){
    choiceNode = document.createElement("option");
    textNode = document.createTextNode(d);
    choiceNode.appendChild(textNode);
    endTimePicker.append(choiceNode);
    console.log("Looping");
  })
};

initStartTimePicker();
initEndTimePicker();

var today = new Date();
//console.log("Now:", today)
var sameDay = true;/* Specify if the startDay and endDay are the same */
var isSameDay = function() {
    startDayStr = document.getElementById('start-date').value;
    endDayStr = document.getElementById('end-date').value;
    /*console.log(startDayStr, "==", endDayStr)*/
    if (startDayStr == endDayStr){ console.log("SameDay=True"); return true;} else {console.log("SameDay=True");return false;}
};

$('#start-date').datetimepicker({
                            format: "MM-DD-YYYY",
                            minDate: today,
                            });

$('#end-date').datetimepicker({
                                format: "MM-DD-YYYY",
                                minDate: today,
                                });

/* CHANGE THE minDate FOR END DATE PICKER */
$('#start-date').on("change.datetimepicker", function(){
    startDayStr = document.getElementById('start-date').value;
    console.log("startDay", startDayStr)
    var endDayInput = document.getElementById('end-date')
    $("#end-date").datetimepicker("minDate", startDayStr);
    if (endDayInput.value == "")
    {
        endDayInput.value = startDayStr;
    }
    if (!isSameDay())
    {
        $('#end-time').datetimepicker("minDate", false);
        initEndTimePicker();
    }
    else{//isSameDay
      adjustEndTimerPicker();
    };
    //console.log("RE-Initialized datepicker");
});

$('#end-date').on("change.datetimepicker", function(){
    startDayStr = document.getElementById('start-date').value;
    if (startDayStr == "")
    {
        document.getElementById('start-date').value = document.getElementById('end-date').value;
    }
    if (!isSameDay())
    {
        $('#end-time').datetimepicker("minDate", false);
        initEndTimePicker();
    }
    else {//isSameDay
      adjustEndTimerPicker();
    };
});

//Update endTimePicker according to startTimePicker
startTimePicker.on("change", function(){
    if (isSameDay()){
        adjustEndTimerPicker();
      }
    else{
      initEndTimePicker();
    };
});

</script>


<script>
$(function () {
  /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
  $("#id_image").change(function () {
    if (this.files && this.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $("#image").attr("src", e.target.result);
        $("#modalCrop").modal("show");
      }
      reader.readAsDataURL(this.files[0]);
    }
  });

  /* SCRIPTS TO HANDLE THE CROPPER BOX */
  var $image = $("#image");
  var cropBoxData;
  var canvasData;
  $("#modalCrop").on("shown.bs.modal", function () {
    $image.cropper({
      viewMode: 1,
      aspectRatio: 7/4.3,
      minCropBoxWidth: 70,
      minCropBoxHeight: 43,
      ready: function () {
        $image.cropper("setCanvasData", canvasData);
        $image.cropper("setCropBoxData", cropBoxData);
      }
    });
  }).on("hidden.bs.modal", function () {
    cropBoxData = $image.cropper("getCropBoxData");
    canvasData = $image.cropper("getCanvasData");
    $image.cropper("destroy");
  });

  $(".js-zoom-in").click(function () {
    $image.cropper("zoom", 0.1);
  });

  $(".js-zoom-out").click(function () {
    $image.cropper("zoom", -0.1);
  });

  /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
  $("#crop_button").click(function () {
    var cropData = $image.cropper("getData");
    $("#id_x").val(cropData["x"]);
    $("#id_y").val(cropData["y"]);
    $("#id_height").val(cropData["height"]);
    $("#id_width").val(cropData["width"]);
    console.log($("#id_x").val(), $("#id_y").val(), $("#id_height").val(), $("#id_width").val());
    $("#modalCrop").modal("hide");
    console.log(cropData["x"], cropData["y"], cropData["height"], cropData["width"])
  });

});


  </script>

<div class="modal fade" id="modalCrop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Crop the photo for the hangout image</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i class="far fa-window-close"></i>
        </button>
      </div>
      <div class="modal-body">
        <img src="" id="image" style="max-width: 100%;">
      </div>
      <div class="modal-footer">
        <div class="btn-group pull-left" role="group">
          <button type="button" class="btn btn-default js-zoom-in">
            <i class="fas fa-search-plus"></i>
          </button>
          <button type="button" class="btn btn-default js-zoom-out">
            <i class="fas fa-search-minus"></i>
          </button>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
        <button type="button" class="btn btn-primary js-crop-and-upload" id="crop_button">Crop image</button>
      </div>
    </div>
  </div>
</div>

        <div id="cropped_image"></div>
    </form>
</div>

{% endblock %}